```{r}
library(tidyverse)
library(tidycensus)
library(sf)
library(pals)
library(biscale)
library(ggrepel)
library(tigris)
options(tigris_use_cache = T)
library(ggnewscale)
library(cowplot)
library(lubridate)
library(slider)
library(hrbrthemes)
library(readxl)
library(scales)
library(RColorBrewer)
library(patchwork)
install.packages(usmap)
library(usmap)

```


```{r, cache=TRU}

cd118 <- congressional_districts(cb = TRUE, resolution = '20m', year = 2022)
```

```{r}
library(readr)
USA_118th_Congressional_Districts_7321755402533503133 <- read_csv("USA_118th_Congressional_Districts_-7321755402533503133.csv")
View(USA_118th_Congressional_Districts_7321755402533503133)
```
```{r}
#| label: load dems and change column

library(readxl)
T1_ag_dems <- read_excel("T1 ag dems.xlsx")
View(T1_ag_dems)


colnames(T1_ag_dems)[2] <- "Last Name"


view(T1_ag_dems)

```

```{r}
#| label: narrowing the data

dem_districts <- T1_ag_dems |>
  inner_join(USA_118th_Congressional_Districts_7321755402533503133, by = "Last Name")

dem_districts <- dem_districts |>
  filter(!(`District ID` %in% c("1308",
         "5103",
         "1707",
         "1707",
         "4813",
         "3708")))

colnames(dem_districts)[5] <- "GEOID"
```

```{r}
#| label: final data frame

cd118_join <- cd118 |>
  inner_join(dem_districts, by = "GEOID")

```

```{r}
#| label: neccesarry for maps

USA <- counties(state = NULL, cb = FALSE, resolution = "500k", year = NULL)


USA <- USA |>
  filter(!(STATEFP %in% c("60", "66", "78", "72", "69", "02", "15")))


USA_bounds <- st_bbox(USA)
```


```{r}
#| label: full country


ggplot() +
  geom_sf(data = USA) +
  geom_sf(data = cd118_join, fill = "red") +
  theme_minimal() +
  lims(
    x = c(USA_bounds$xmin, USA_bounds$xmax),
    y = c(USA_bounds$ymin, USA_bounds$ymax)) 
```
```{r}
#| label: CT Map

ggplot() +
  geom_sf(data = USA |>
            filter(STATEFP == "09")) +
  geom_sf(data = cd118_join |>
            filter(STATEFP == "09"), linewidth = 2) +
  theme_minimal()

```
```{r}
#| label: Washington Map


ggplot() +
  geom_sf(data = USA |>
            filter(STATEFP == "53")) +
  geom_sf(data = cd118_join |>
            filter(STATEFP == "53"), fill = "red", linewidth = 2) +
  theme_minimal()
```


```{r}
install.packages("usmap")
library(usmap) #import the package
library(ggplot2) #use ggplot2 to add layer for visualization
```
```{r}

us_states <- tigris::states(class = "sf")

us_states <- us_states |>
  filter(!(STATEFP %in% c("60", "66", "78", "72", "69", "02", "15")))


GT_states <- us_states |>
  right_join(Chairman_Thompson_Travel_2021_2023, by = "NAME")

colnames(Chairman_Thompson_Travel_2021_2023)[6] <- "NAME"

GT_states <- GT_states |>
  mutate(INTPTLAT = gsub("\\+", "", INTPTLAT),
         INTPTLON = gsub("\\-0", "-", INTPTLON)) |>
  mutate(INTPTLON = as.numeric(INTPTLON),
         INTPTLAT = as.numeric(INTPTLAT))


```


```{r}
ggplot() +
  geom_sf(data = us_states, fill = "#4B6D34", color = "white") +
  ggrepel::geom_label_repel(
    data = GT_states,
    aes(label = NAME, x = INTPTLON, y = INTPTLAT),
    box.padding = 0.35,
    segment.color = "black",
    segment.size = 0.2,
    seed = 1234,
    force = 8,
    color = "black",
    fill = "lightyellow",
    max.overlaps = Inf  # Allow unlimited overlaps for labeling
  ) +
  labs(
    title = "States Chairman Thompson Visited",
    subtitle = "Since Becoming Republican Leader of the Committee",
    x = NULL,
    y = NULL
  ) +
  theme_minimal() +  # Use minimal theme for clean appearance
  theme(
    plot.title = element_text(size = 28, face = "bold", hjust = 0.5, family = "Serif"),  # Larger title
    plot.subtitle = element_text(size = 18, hjust = 0.5),  # Smaller subtitle
    panel.grid = element_blank(),
    plot.background = element_rect(fill = "#FFFFFF"),  # Light gray background
    axis.text = element_blank(),  # Hide axis text
    axis.ticks = element_blank(),  # Hide axis ticks
    legend.position = "none"  # Remove legend
  )
```





```{r}
ggplot() +
  geom_sf(data = us_states) +
  ggrepel::geom_label_repel(
    data = GT_states,
    aes(label = NAME, x = INTPTLON, y = INTPTLAT),
     min.segment.length = 0, 
    seed = 1234,
    force = 20,
     max.overlaps = Inf) +
  theme_void() + 
  labs(
    title = "States Chairman Thompson Visited",
    subtitle = "since becoming Republican leader of the Committee",
    x = " " ,
    y = " ")

```




```{r}
glimpse(GT_states)
```
```{r}
PA <- us_states[us_states$NAME == "Pennsylvania", ]
```


```{r}
ggplot() +
  geom_sf(data = us_states, fill = "#4B6D34", color = "white") +
  geom_sf(data = PA, fill = "#C3A571") +
  geom_point(data = GT_coords, 
             aes(x = Longitude, y = Latitude),
             shape = 23, fill = "#C3A571", size = 4) +
  labs(
    title = "States Chairman Thompson Visited",
    subtitle = "Since Becoming Republican Leader of the Committee",
    x = NULL,
    y = NULL
  ) +
  theme_minimal() +  # Use minimal theme for clean appearance
  theme(
    plot.title = element_text(size = 28, face = "bold", hjust = 0.5, family = "Serif"),  # Larger title
    plot.subtitle = element_text(size = 18, hjust = 0.5),  # Smaller subtitle
    panel.grid = element_blank(),
    plot.background = element_rect(fill = "#FFFFFF"),  # Light gray background
    axis.text = element_blank(),  # Hide axis text
    axis.ticks = element_blank(),  # Hide axis ticks
    legend.position = "none"  # Remove legend
  )
```

```{r}

glimpse(GT_coords)

GT_coords <- na.omit(GT_coords)


GT_coords |>
  mutate(Longitude = as.numeric(Longitude),
         Latitude = as.numeric(Latitude))


GT_coords <- GT_coords |> 
  mutate_if(is.numeric, funs(. * -1))

GT_coords <- GT_coords |>
  mutate(Latitude = Latitude*(-1))


GT_coords <- GT_coords |>
  filter(!(Latitude %in% c(35.81263, 41.24920)))
```


